---
title: "NHANES_special_topics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(rnhanesdata)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)

load("PAXINTEN_C.rda")
load("PAXINTEN_D.rda")
load("Covariate_C.rda")
load("Covariate_D.rda")
load("FLAGS_C.rda")
load("FLAGS_D.rda")

```



```{r summary stats and basics}
#colnames(PAXINTEN_C)

# View number of inadeequate rows
ggc1 = ggplot(data = PAXINTEN_C, aes(x = PAXCAL))+geom_bar(aes(fill = PAXCAL==1),position = position_dodge(width = 0.8), width=0.5)+
  labs(title = "PAXCAL Distribution in 2003-2004")+
  scale_fill_discrete(name = NULL,labels = c("Possibly Inaccurate","Adequate Data"))+
  theme_bw()
ggc2 = ggplot(data = PAXINTEN_C, aes(x = PAXSTAT))+geom_bar(aes(fill = PAXSTAT==1),position = position_dodge(width = 0.8), width=0.5)+
  labs(title = "PAXSTAT Distribution in 2003-2004")+
  scale_fill_discrete(name = NULL,labels = c("Possibly Inaccurate","Adequate Data"))+
  theme_bw()
ggd1 = ggplot(data = PAXINTEN_D, aes(x = PAXCAL))+geom_bar(aes(fill = PAXCAL==1),position = position_dodge(width = 0.8), width=0.5)+
  labs(title = "PAXCAL Distribution in 2005-2006")+
  scale_fill_discrete(name = NULL,labels = c("Possibly Inaccurate","Adequate Data"))+
  theme_bw()
ggd2 = ggplot(data = PAXINTEN_D, aes(x = PAXSTAT))+geom_bar(aes(fill = PAXSTAT==1),position = position_dodge(width = 0.8), width=0.5)+
  labs(title = "PAXSTAT Distribution in 2005-2006")+
  scale_fill_discrete(name = NULL, labels = c( "Possibly Inaccurate","Adequate Data"))+
  theme_bw()

ggarrange(ggc1,ggd1, ncol = 2,common.legend = T, legend = "bottom")
ggarrange(ggc2,ggd2, ncol = 2, common.legend = T, legend = "bottom")


```


```{r}
mn.na = function(var) {
  return(mean(var, na.rm = T))
}

dat = rbind(PAXINTEN_C,PAXINTEN_D)

wkdy = dat[which(dat$WEEKDAY%in% c(2:6)),]
wknd = dat[which(dat$WEEKDAY%in% c(1,7)),]

x1 = data.frame(apply(wkdy[,c(6:1445)], 2, mn.na))
colnames(x1) = "val"
x1$time = as.numeric(substr(rownames(x1),4,stop = nchar(rownames(x1))))

x2 = data.frame(apply(wknd[,c(6:1445)], 2, mn.na))
colnames(x2) = "val"
x2$time = as.numeric(substr(rownames(x2),4,stop = nchar(rownames(x2))))


gg1 =ggplot(data = x1, aes(x = time, y = val ))+geom_path(size = 0.5)+
  labs(y = "Average Activity Count")+
  scale_x_continuous(breaks = seq(0, max(x1$time), by = 120))
  
gg2 =ggplot(data = x2, aes(x = time, y = val ))+geom_path(size = 0.5)+
  labs(y = "Average Activity Count")+
  scale_x_continuous(breaks = seq(0, max(x2$time), by = 120))

gg1 
gg2
```


```{r}
wkdy2 = dat[which(dat$WEEKDAY%in% c(1:6)),]
wkdy2[which(wkdy2$WEEKDAY==1),c(6:1145)]=NA
wkdy2[which(wkdy2$WEEKDAY==6),c(1146:1445)]=NA

wknd2 = dat[which(dat$WEEKDAY%in% c(1,6:7)),]
wknd2[which(wknd2$WEEKDAY==1),c(1146:1445)]=NA
wknd2[which(wknd2$WEEKDAY==6),c(6:1145)]=NA



w1 = data.frame(apply(wkdy2[,c(6:1445)], 2, mn.na))
colnames(w1) = "val"
w1$time = as.numeric(substr(rownames(w1),4,stop = nchar(rownames(w1))))

w2 = data.frame(apply(wknd2[,c(6:1445)], 2, mn.na))
colnames(w2) = "val"
w2$time = as.numeric(substr(rownames(w2),4,stop = nchar(rownames(w2))))


gg1 =ggplot(data = w1, aes(x = time, y = val ))+geom_path(size = 0.5)+
  labs(y = "Average Activity Count")+
  scale_x_continuous(breaks = seq(0, max(w1$time), by = 120))
  
gg2 =ggplot(data = w2, aes(x = time, y = val ))+geom_path(size = 0.5)+
  labs(y = "Average Activity Count")+
  scale_x_continuous(breaks = seq(0, max(w2$time), by = 120))

gg1 
gg2
```

```{r}
flags = rbind(Flags_C,Flags_D)





```


